name: catalog-api-build-provision-deploy-arm

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - apps/catalog-api/*

trigger: none
pr: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scIaC
  folder: apps/catalog-api/api/
  appservice: foodcatalog-arm
  plan: foodplan-iac
  rg: az400-m06-IaC

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: BuildProvision
    displayName: Build and Provision
    jobs:
      - job: Build
        steps:
          - template: templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(folder)
      
      - job: Provision

        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'ARM Template Deployment'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: $(azSubscription)
            subscriptionId: '78033352-805c-4acd-af80-f8f95083268d'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(rg)'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '$(System.DefaultWorkingDirectory)/deploy/arm/api-azuredeploy.json'
            overrideParameters: '-webapp $(appservice) -serviceplan $(plan)'
            deploymentMode: 'Incremental'
  
  - stage: Deploy
    displayName: Deploy
    dependsOn: BuildProvision

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: catalog-api-arm
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azSubscription)
                    appType: "webApp"
                    WebAppName: $(appservice)
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"