name: catalog-api-build-provision-deploy-cli

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - apps/catalog-api/*

trigger: none
pr: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scIaC
  folder: apps/catalog-api/api/
  appservice: foodcatalog-cli

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: BuildProvision
    displayName: Build and Provision
    jobs:
      - job: Build
        steps:
          - template: templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(folder)
      
      - job: Provision
        steps:
        - task: AzureCLI@2
          displayName: 'Provision AppService'
          inputs:
            azureSubscription: '$(azSubscription)'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: '$(System.DefaultWorkingDirectory)/deploy/az-cli/create-api.sh'
            arguments: $(appservice)

  - stage: Deploy
    displayName: Deploy
    dependsOn: BuildProvision

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: catalog-api-prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azSubscription)
                    appType: "webApp"
                    WebAppName: $(appservice)
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"