name: ng-build-deploy-app-service-file-transform.yml

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - FoodUI

trigger: none
pr: none

variables:
  azSubscription: scFood
  path: food-ui/
  env: 'file-replacement'
  appservice: 'foodui'
  # apiurl value will be used in FileTransform@1
  apiurl: 'https://foodapi-$(env).azurewebsites.net/'

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    displayName: Build and Provision
    jobs:
      - job: ngBuild

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node 16"
            
          - task: FileTransform@1
            displayName: Replace Api Url
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)/**/assets'
              fileType: 'json'
              targetFiles: '**/app-config.json'

          - script: npm i -g @angular/cli
            displayName: "Install Angular CLI"
            
          - task: Cache@2
            inputs:
                key: '$(System.DefaultWorkingDirectory)/$(path)/package-lock.json'
                path: '$(System.DefaultWorkingDirectory)/$(path)/node_modules'
                cacheHitVar: 'ngCacheRestored'

          - script: npm i            
            displayName: "Install Dependencies"
            workingDirectory: $(path)
            condition: eq(variables['ngCacheRestored'],False)

          - script: ng b -c production
            displayName: "Create Build"
            workingDirectory: $(path)

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/$(path)dist/'
              ArtifactName: 'ngapp'
      
      - job: Provision

        steps:
        
        - task: AzureCLI@2
          displayName: 'Provision AppService'
          inputs:
            azureSubscription: '$(azSubscription)'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: '$(System.DefaultWorkingDirectory)/az-cli/create-ui-webapp.sh'
            arguments: '$(env)'

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifactName: ngapp
                    downloadPath: "$(System.DefaultWorkingDirectory)"
                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: '$(azSubscription)'
                    appType: 'webApp'
                    WebAppName: '$(appservice)-$(env)'
                    packageForLinux: '$(System.DefaultWorkingDirectory)/food-ui/'