name: process issues - github script sample

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ":thumbsup: Thank you for reporting this issue"
            })
            
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - if: join(github.event.issue.labels) == ''
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-classification']
            })
            
  auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1
              with:
                  repo-token: ${{ secrets.ISSUESSECRET }}
                  assignees: ${{ secrets.DEFAULT_ISSUE_ASSIGNEE }}
